2017-03-28 20:12:12 [twisted] CRITICAL: Unhandled error in Deferred:
2017-03-28 20:12:12 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "D:\Program Files\Anaconda3\envs\scrapy_test\lib\site-packages\twisted\internet\defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "D:\Program Files\Anaconda3\envs\scrapy_test\lib\site-packages\scrapy\crawler.py", line 72, in crawl
    self.engine = self._create_engine()
  File "D:\Program Files\Anaconda3\envs\scrapy_test\lib\site-packages\scrapy\crawler.py", line 97, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "D:\Program Files\Anaconda3\envs\scrapy_test\lib\site-packages\scrapy\core\engine.py", line 68, in __init__
    self.downloader = downloader_cls(crawler)
  File "D:\Program Files\Anaconda3\envs\scrapy_test\lib\site-packages\scrapy\core\downloader\__init__.py", line 88, in __init__
    self.middleware = DownloaderMiddlewareManager.from_crawler(crawler)
  File "D:\Program Files\Anaconda3\envs\scrapy_test\lib\site-packages\scrapy\middleware.py", line 58, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "D:\Program Files\Anaconda3\envs\scrapy_test\lib\site-packages\scrapy\middleware.py", line 36, in from_settings
    mw = mwcls.from_crawler(crawler)
  File "D:\Program Files\Anaconda3\envs\scrapy_test\lib\site-packages\scrapoxy\downloadmiddlewares\scale.py", line 39, in from_crawler
    return cls(crawler)
  File "D:\Program Files\Anaconda3\envs\scrapy_test\lib\site-packages\scrapoxy\downloadmiddlewares\scale.py", line 28, in __init__
    crawler.settings.get('API_SCRAPOXY_PASSWORD')
  File "D:\Program Files\Anaconda3\envs\scrapy_test\lib\site-packages\scrapoxy\commander.py", line 16, in __init__
    self._password = base64.b64encode(password)
  File "D:\Program Files\Anaconda3\envs\scrapy_test\lib\base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'
